require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CheilOrgsController do

  # This should return the minimal set of attributes required to create a valid
  # CheilOrg. As you add validations to CheilOrg, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cheil_orgs as @cheil_orgs" do
      cheil_org = CheilOrg.create! valid_attributes
      get :index
      assigns(:cheil_orgs).should eq([cheil_org])
    end
  end

  describe "GET show" do
    it "assigns the requested cheil_org as @cheil_org" do
      cheil_org = CheilOrg.create! valid_attributes
      get :show, :id => cheil_org.id
      assigns(:cheil_org).should eq(cheil_org)
    end
  end

  describe "GET new" do
    it "assigns a new cheil_org as @cheil_org" do
      get :new
      assigns(:cheil_org).should be_a_new(CheilOrg)
    end
  end

  describe "GET edit" do
    it "assigns the requested cheil_org as @cheil_org" do
      cheil_org = CheilOrg.create! valid_attributes
      get :edit, :id => cheil_org.id
      assigns(:cheil_org).should eq(cheil_org)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CheilOrg" do
        expect {
          post :create, :cheil_org => valid_attributes
        }.to change(CheilOrg, :count).by(1)
      end

      it "assigns a newly created cheil_org as @cheil_org" do
        post :create, :cheil_org => valid_attributes
        assigns(:cheil_org).should be_a(CheilOrg)
        assigns(:cheil_org).should be_persisted
      end

      it "redirects to the created cheil_org" do
        post :create, :cheil_org => valid_attributes
        response.should redirect_to(CheilOrg.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cheil_org as @cheil_org" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheilOrg.any_instance.stub(:save).and_return(false)
        post :create, :cheil_org => {}
        assigns(:cheil_org).should be_a_new(CheilOrg)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheilOrg.any_instance.stub(:save).and_return(false)
        post :create, :cheil_org => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cheil_org" do
        cheil_org = CheilOrg.create! valid_attributes
        # Assuming there are no other cheil_orgs in the database, this
        # specifies that the CheilOrg created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CheilOrg.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => cheil_org.id, :cheil_org => {'these' => 'params'}
      end

      it "assigns the requested cheil_org as @cheil_org" do
        cheil_org = CheilOrg.create! valid_attributes
        put :update, :id => cheil_org.id, :cheil_org => valid_attributes
        assigns(:cheil_org).should eq(cheil_org)
      end

      it "redirects to the cheil_org" do
        cheil_org = CheilOrg.create! valid_attributes
        put :update, :id => cheil_org.id, :cheil_org => valid_attributes
        response.should redirect_to(cheil_org)
      end
    end

    describe "with invalid params" do
      it "assigns the cheil_org as @cheil_org" do
        cheil_org = CheilOrg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheilOrg.any_instance.stub(:save).and_return(false)
        put :update, :id => cheil_org.id, :cheil_org => {}
        assigns(:cheil_org).should eq(cheil_org)
      end

      it "re-renders the 'edit' template" do
        cheil_org = CheilOrg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheilOrg.any_instance.stub(:save).and_return(false)
        put :update, :id => cheil_org.id, :cheil_org => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cheil_org" do
      cheil_org = CheilOrg.create! valid_attributes
      expect {
        delete :destroy, :id => cheil_org.id
      }.to change(CheilOrg, :count).by(-1)
    end

    it "redirects to the cheil_orgs list" do
      cheil_org = CheilOrg.create! valid_attributes
      delete :destroy, :id => cheil_org.id
      response.should redirect_to(cheil_orgs_url)
    end
  end

end
