require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PayersController do

  # This should return the minimal set of attributes required to create a valid
  # Payer. As you add validations to Payer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all payers as @payers" do
      payer = Payer.create! valid_attributes
      get :index
      assigns(:payers).should eq([payer])
    end
  end

  describe "GET show" do
    it "assigns the requested payer as @payer" do
      payer = Payer.create! valid_attributes
      get :show, :id => payer.id
      assigns(:payer).should eq(payer)
    end
  end

  describe "GET new" do
    it "assigns a new payer as @payer" do
      get :new
      assigns(:payer).should be_a_new(Payer)
    end
  end

  describe "GET edit" do
    it "assigns the requested payer as @payer" do
      payer = Payer.create! valid_attributes
      get :edit, :id => payer.id
      assigns(:payer).should eq(payer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Payer" do
        expect {
          post :create, :payer => valid_attributes
        }.to change(Payer, :count).by(1)
      end

      it "assigns a newly created payer as @payer" do
        post :create, :payer => valid_attributes
        assigns(:payer).should be_a(Payer)
        assigns(:payer).should be_persisted
      end

      it "redirects to the created payer" do
        post :create, :payer => valid_attributes
        response.should redirect_to(Payer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payer as @payer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Payer.any_instance.stub(:save).and_return(false)
        post :create, :payer => {}
        assigns(:payer).should be_a_new(Payer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Payer.any_instance.stub(:save).and_return(false)
        post :create, :payer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payer" do
        payer = Payer.create! valid_attributes
        # Assuming there are no other payers in the database, this
        # specifies that the Payer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Payer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => payer.id, :payer => {'these' => 'params'}
      end

      it "assigns the requested payer as @payer" do
        payer = Payer.create! valid_attributes
        put :update, :id => payer.id, :payer => valid_attributes
        assigns(:payer).should eq(payer)
      end

      it "redirects to the payer" do
        payer = Payer.create! valid_attributes
        put :update, :id => payer.id, :payer => valid_attributes
        response.should redirect_to(payer)
      end
    end

    describe "with invalid params" do
      it "assigns the payer as @payer" do
        payer = Payer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Payer.any_instance.stub(:save).and_return(false)
        put :update, :id => payer.id, :payer => {}
        assigns(:payer).should eq(payer)
      end

      it "re-renders the 'edit' template" do
        payer = Payer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Payer.any_instance.stub(:save).and_return(false)
        put :update, :id => payer.id, :payer => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payer" do
      payer = Payer.create! valid_attributes
      expect {
        delete :destroy, :id => payer.id
      }.to change(Payer, :count).by(-1)
    end

    it "redirects to the payers list" do
      payer = Payer.create! valid_attributes
      delete :destroy, :id => payer.id
      response.should redirect_to(payers_url)
    end
  end

end
