require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VendorOrgsController do

  # This should return the minimal set of attributes required to create a valid
  # VendorOrg. As you add validations to VendorOrg, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all vendor_orgs as @vendor_orgs" do
      vendor_org = VendorOrg.create! valid_attributes
      get :index
      assigns(:vendor_orgs).should eq([vendor_org])
    end
  end

  describe "GET show" do
    it "assigns the requested vendor_org as @vendor_org" do
      vendor_org = VendorOrg.create! valid_attributes
      get :show, :id => vendor_org.id
      assigns(:vendor_org).should eq(vendor_org)
    end
  end

  describe "GET new" do
    it "assigns a new vendor_org as @vendor_org" do
      get :new
      assigns(:vendor_org).should be_a_new(VendorOrg)
    end
  end

  describe "GET edit" do
    it "assigns the requested vendor_org as @vendor_org" do
      vendor_org = VendorOrg.create! valid_attributes
      get :edit, :id => vendor_org.id
      assigns(:vendor_org).should eq(vendor_org)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VendorOrg" do
        expect {
          post :create, :vendor_org => valid_attributes
        }.to change(VendorOrg, :count).by(1)
      end

      it "assigns a newly created vendor_org as @vendor_org" do
        post :create, :vendor_org => valid_attributes
        assigns(:vendor_org).should be_a(VendorOrg)
        assigns(:vendor_org).should be_persisted
      end

      it "redirects to the created vendor_org" do
        post :create, :vendor_org => valid_attributes
        response.should redirect_to(VendorOrg.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vendor_org as @vendor_org" do
        # Trigger the behavior that occurs when invalid params are submitted
        VendorOrg.any_instance.stub(:save).and_return(false)
        post :create, :vendor_org => {}
        assigns(:vendor_org).should be_a_new(VendorOrg)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VendorOrg.any_instance.stub(:save).and_return(false)
        post :create, :vendor_org => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vendor_org" do
        vendor_org = VendorOrg.create! valid_attributes
        # Assuming there are no other vendor_orgs in the database, this
        # specifies that the VendorOrg created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VendorOrg.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => vendor_org.id, :vendor_org => {'these' => 'params'}
      end

      it "assigns the requested vendor_org as @vendor_org" do
        vendor_org = VendorOrg.create! valid_attributes
        put :update, :id => vendor_org.id, :vendor_org => valid_attributes
        assigns(:vendor_org).should eq(vendor_org)
      end

      it "redirects to the vendor_org" do
        vendor_org = VendorOrg.create! valid_attributes
        put :update, :id => vendor_org.id, :vendor_org => valid_attributes
        response.should redirect_to(vendor_org)
      end
    end

    describe "with invalid params" do
      it "assigns the vendor_org as @vendor_org" do
        vendor_org = VendorOrg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VendorOrg.any_instance.stub(:save).and_return(false)
        put :update, :id => vendor_org.id, :vendor_org => {}
        assigns(:vendor_org).should eq(vendor_org)
      end

      it "re-renders the 'edit' template" do
        vendor_org = VendorOrg.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VendorOrg.any_instance.stub(:save).and_return(false)
        put :update, :id => vendor_org.id, :vendor_org => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vendor_org" do
      vendor_org = VendorOrg.create! valid_attributes
      expect {
        delete :destroy, :id => vendor_org.id
      }.to change(VendorOrg, :count).by(-1)
    end

    it "redirects to the vendor_orgs list" do
      vendor_org = VendorOrg.create! valid_attributes
      delete :destroy, :id => vendor_org.id
      response.should redirect_to(vendor_orgs_url)
    end
  end

end
